services:
  - type: web
    name: text-leech-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK
        value: "False"
      - key: PORT
        value: "8080"
