services:
  - type: web
    name: text-leech-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK
        value: "False"
      - key: PORT
        value: "10000"
